# Statistical Inference Course Project
## Overview
This is a Coursera Statistical Inference project in which the aim is to compare the exponential distribution with lambda = 0.2 and compare it against the Central Limit Theorem using 1000 simulations of the averages of 40 exponentials.

Illustrate via simulation and associated explanatory text the properties of the distribution of the mean of 40 exponentials.  You should
1. Show the sample mean and compare it to the theoretical mean of the distribution.
2. Show how variable the sample is (via variance) and compare it to the theoretical variance of the distribution.
3. Show that the distribution is approximately normal.

In point 3, focus on the difference between the distribution of a large collection of random exponentials and the distribution of a large collection of averages of 40 exponentials. 

## Setting up the Simulations
```{r message=FALSE}
library(ggplot2)

set.seed(1234)
nosim <- 1000        
sampleSize <- 40 
lambda <- 0.2   
dist <- matrix(rexp(sampleSize * nosim, rate = 1/lambda), ncol = sampleSize, nrow=nosim)
dist.means <- rowMeans(dist) 
```

## Sample Means vs. Theoretical Means

## Sample Variance vs. Theoretical Variance

## Distribution